import { StyledContext } from './helpers/createStyledContext';
import type { GetRef } from './interfaces/GetRef';
import type { GetBaseStyles, GetFinalProps, GetNonStyledProps, GetProps, GetVariantProps, GetVariantValues, StaticConfig, StylableComponent, TamaguiComponent, ThemeValueByCategory, VariantDefinitions, VariantSpreadFunction } from './types';
type AreVariantsUndefined<Variants> = Variants extends void ? true : false;
type GetVariantAcceptedValues<V> = V extends Object ? {
    [Key in keyof V]?: V[Key] extends VariantSpreadFunction<any, infer Val> ? Val : GetVariantValues<keyof V[Key]>;
} : undefined;
export declare function styled<ParentComponent extends StylableComponent, Variants extends VariantDefinitions<ParentComponent> | void = void, StyledStaticConfig extends Partial<StaticConfig> = {}>(ComponentIn: ParentComponent, options?: GetProps<ParentComponent> & {
    name?: string;
    variants?: Variants | undefined;
    defaultVariants?: GetVariantAcceptedValues<Variants>;
    context?: StyledContext;
    acceptsClassName?: boolean;
}, staticExtractionOptions?: StyledStaticConfig): (ParentComponent extends TamaguiComponent ? AreVariantsUndefined<Variants> extends true ? true : false : false) extends true ? ParentComponent : TamaguiComponent<ParentComponent extends TamaguiComponent ? {
    expandLater: true;
} : GetFinalProps<GetNonStyledProps<ParentComponent>, GetBaseStyles<ParentComponent> & (AreVariantsUndefined<AreVariantsUndefined<Variants> extends true ? {} : GetVariantAcceptedValues<Variants>> extends true ? GetVariantProps<ParentComponent> : AreVariantsUndefined<GetVariantProps<ParentComponent>> extends true ? AreVariantsUndefined<Variants> extends true ? {} : GetVariantAcceptedValues<Variants> : { [Key in keyof GetVariantProps<ParentComponent> | keyof (AreVariantsUndefined<Variants> extends true ? {} : GetVariantAcceptedValues<Variants>)]?: (Key extends keyof GetVariantProps<ParentComponent> ? GetVariantProps<ParentComponent>[Key] : undefined) | (Key extends keyof (AreVariantsUndefined<Variants> extends true ? {} : GetVariantAcceptedValues<Variants>) ? (AreVariantsUndefined<Variants> extends true ? {} : GetVariantAcceptedValues<Variants>)[Key] : undefined) | undefined; }) & (StyledStaticConfig["acceptTokens"] extends Object ? { [Key_1 in keyof StyledStaticConfig["acceptTokens"]]: ThemeValueByCategory<StyledStaticConfig["acceptTokens"][Key_1]>; } : {})>, GetRef<ParentComponent>, GetNonStyledProps<ParentComponent>, GetBaseStyles<ParentComponent> & (StyledStaticConfig["acceptTokens"] extends Object ? { [Key_1 in keyof StyledStaticConfig["acceptTokens"]]: ThemeValueByCategory<StyledStaticConfig["acceptTokens"][Key_1]>; } : {}), AreVariantsUndefined<AreVariantsUndefined<Variants> extends true ? {} : GetVariantAcceptedValues<Variants>> extends true ? GetVariantProps<ParentComponent> : AreVariantsUndefined<GetVariantProps<ParentComponent>> extends true ? AreVariantsUndefined<Variants> extends true ? {} : GetVariantAcceptedValues<Variants> : { [Key in keyof GetVariantProps<ParentComponent> | keyof (AreVariantsUndefined<Variants> extends true ? {} : GetVariantAcceptedValues<Variants>)]?: (Key extends keyof GetVariantProps<ParentComponent> ? GetVariantProps<ParentComponent>[Key] : undefined) | (Key extends keyof (AreVariantsUndefined<Variants> extends true ? {} : GetVariantAcceptedValues<Variants>) ? (AreVariantsUndefined<Variants> extends true ? {} : GetVariantAcceptedValues<Variants>)[Key] : undefined) | undefined; }, { [Key_2 in Exclude<keyof ParentComponent, "defaultProps" | "propTypes" | "staticConfig" | "extractable" | "styleable" | "$$typeof">]: ParentComponent[Key_2]; }>;
export {};
//# sourceMappingURL=styled.d.ts.map